=== josiasvfigueredo1985/restsharp-serverest/DesafioAutomacaoRestSharp/Schemas/Pagamento.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "dataPagamento": {
        "type": "string"
      },
      "formaPagamento": {
        "type": "object",
        "properties": {
          "pix": {
            "type": "string"
          },
          "boleto": {
            "type": "string"
          },
          "credito": {
            "type": "object",
            "properties": {
              "credito_status": {
                "type": "string"
              },
              "qteParcelas": {
                "type": "string"
              },
              "juros": {
                "type": "string"
              }
            }
          }
        }
      },
      "precoTotal": {
        "type": "string"
      },
      "quantidadeTotal": {
        "type": "string"
      },
      "idUsuario": {
        "type": "string"
      },
      "_id": {
        "type": "string"
      },
      "idPagamento": {
        "type": "string"
      }
    }
  }
}

=== josiasvfigueredo1985/restsharp-serverest/DesafioAutomacaoRestSharp/DesafioAutomacaoRestSharp/Jsons/Pagamento.json
{
  "dataPagamento": "$dataPagamento",
  "formaPagamento": {
    "pix": "$pix",
    "boleto": "$boleto",
    "credito": {
      "credito_status": "$credito_status",
      "qteParcelas": "$qteParcelas",
      "juros": "$juros"
    }
  },
  "precoTotal": "$precoTotal",
  "quantidadeTotal": "$quantidadeTotal",
  "idUsuario": "$idUsuario",
  "_id": "$_id"
}
